"""Bind calls to the required and optional parameters of their method signatures.

Signatures come from the module's own AST (methods of the module, static methods of its
structures and enums called as `Type.Method(...)`). The check is per-file; catalog
manager names guard implicit overloads. A finding is proven: the callee is resolved to exactly one local method and the
arguments do not bind to its required and optional parameters.

Left alone on purpose:
- named calls to module methods also generated by the platform (implicit overloads);
- callee names shadowed by a local declaration or parameter anywhere in the module
  (a variable may hold a lambda with its own arity);
- overloaded method names (binding requires overload resolution).

Cross-module calls (`Модуль.Метод(...)`) are covered by the project-scope twin
`code/call-arity-cross` below - it resolves the base name to another module of the
project and checks against that module's signatures.
"""

from __future__ import annotations

from collections.abc import Iterable
from functools import lru_cache

from xbsl import dataset, i18n, terms
from xbsl import parser as P
from xbsl.diagnostics import Diagnostic, Severity
from xbsl.engine import SourceFile, rule
from xbsl.lexer import linemap
from xbsl.parser import parse
from xbsl.rules.semantics import _manager_members

MESSAGES = {
    "code/call-arity.title": {
        "ru": "Число аргументов не по сигнатуре",
        "en": "Argument count does not match the signature",
    },
    "code/call-arity.too-many": {
        "ru": "Вызов {name}: передано аргументов – {got}, метод принимает не больше {max}",
        "en": "Call of {name}: {got} arguments passed, the method takes at most {max}",
    },
    "code/call-arity.too-few": {
        "ru": "Вызов {name}: передано аргументов – {got}, методу нужно не меньше {min}",
        "en": "Call of {name}: {got} arguments passed, the method needs at least {min}",
    },
    "code/call-arity.duplicate": {
        "ru": "Вызов {name}: параметр {param} передан повторно",
        "en": "Call of {name}: parameter {param} is supplied more than once",
    },
    "code/call-arity.unknown": {
        "ru": "Вызов {name}: неизвестный параметр {param}",
        "en": "Call of {name}: unknown parameter {param}",
    },
    "code/call-arity.positional-after-named": {
        "ru": "Вызов {name}: позиционный аргумент после именованного",
        "en": "Call of {name}: positional argument follows a named argument",
    },
    "code/call-arity.missing": {
        "ru": "Вызов {name}: не передан обязательный параметр {param}",
        "en": "Call of {name}: required parameter {param} is missing",
    },
    "code/call-arity-cross.title": {
        "ru": "Число аргументов кросс-модульного вызова не по сигнатуре",
        "en": "Argument count of a cross-module call does not match the signature",
    },
}
i18n.register(MESSAGES)


Signature = tuple[tuple[str, bool], ...]


def _signature(m: P.Method) -> Signature:
    return tuple((p.name, p.default is None) for p in m.params)


@lru_cache(maxsize=1)
def _generated_method_names() -> frozenset[str]:
    """Known singleton overloads absent from a module's AST, in both spellings.

    File scope cannot prove the metadata kind, so a matching module method is
    conservatively left to the compiler. Explicit static structure methods are
    unaffected. The source is the generated catalog, never a name whitelist.
    """
    names = {
        name for entry in _manager_members().values()
        for name in (*entry.get("methods", ()), *entry.get("members", ()))
    }
    return frozenset(names | {terms.common_english(name) or name for name in names})


dataset.register_reset(_generated_method_names.cache_clear)


def _argument_error(
    name: str, sig: Signature, args: tuple[str | None, ...], generated: bool = False,
) -> str | None:
    """Bind positional and named arguments, returning the first proven error."""
    required = sum(required for _, required in sig)
    got, total = len(args), len(sig)
    has_named = any(arg is not None for arg in args)
    if generated and has_named:
        return None
    if not has_named:
        if got > total:
            return i18n.t("code/call-arity.too-many", name=name, got=got, max=total)
        if got < required:
            return i18n.t("code/call-arity.too-few", name=name, got=got, min=required)
        if generated:
            return None
    params = {param for param, _ in sig}
    if len(params) != total:
        return None  # a broken signature cannot prove a unique binding
    supplied: set[str] = set()
    named = False
    for index, arg in enumerate(args):
        if arg is None:
            if named:
                return i18n.t("code/call-arity.positional-after-named", name=name)
            if index < total:
                supplied.add(sig[index][0])
            continue
        named = True
        if arg not in params:
            return i18n.t("code/call-arity.unknown", name=name, param=arg)
        if arg in supplied:
            return i18n.t("code/call-arity.duplicate", name=name, param=arg)
        supplied.add(arg)
    if got > total:
        return i18n.t("code/call-arity.too-many", name=name, got=got, max=total)
    for param, needed in sig:
        if needed and param not in supplied:
            return i18n.t("code/call-arity.missing", name=name, param=param)
    return None


def _walk_expr(expr: P.Expr | None, calls: list[P.Call], names: set[str]) -> None:
    if expr is None:
        return
    if isinstance(expr, P.Name):
        return
    if isinstance(expr, P.Call):
        calls.append(expr)
        _walk_expr(expr.callee, calls, names)
        for arg in expr.args:
            _walk_expr(arg.value, calls, names)
        return
    if isinstance(expr, P.Lambda):
        names.update(p.name for p in expr.params)
        if isinstance(expr.body_expr, P.Expr):
            _walk_expr(expr.body_expr, calls, names)
        elif isinstance(expr.body_expr, P.Assign):
            _walk_expr(expr.body_expr.target, calls, names)
            _walk_expr(expr.body_expr.value, calls, names)
        if expr.body_stmts is not None:
            _walk_body(expr.body_stmts, calls, names)
        return
    if isinstance(expr, P.Unary):
        _walk_expr(expr.operand, calls, names)
    elif isinstance(expr, P.Binary):
        _walk_expr(expr.left, calls, names)
        _walk_expr(expr.right, calls, names)
    elif isinstance(expr, P.Compare):
        _walk_expr(expr.first, calls, names)
        for _op, right in expr.rest:
            _walk_expr(right, calls, names)
    elif isinstance(expr, (P.IsType, P.AsType, P.NonNull)):
        _walk_expr(expr.operand, calls, names)
    elif isinstance(expr, P.Ternary):
        _walk_expr(expr.cond, calls, names)
        _walk_expr(expr.then, calls, names)
        _walk_expr(expr.otherwise, calls, names)
    elif isinstance(expr, P.Coalesce):
        _walk_expr(expr.left, calls, names)
        _walk_expr(expr.right, calls, names)
    elif isinstance(expr, P.Member):
        _walk_expr(expr.obj, calls, names)
    elif isinstance(expr, P.Index):
        _walk_expr(expr.obj, calls, names)
        _walk_expr(expr.index, calls, names)
    elif isinstance(expr, P.New):
        if expr.args:
            for arg in expr.args:
                _walk_expr(arg.value, calls, names)
    elif isinstance(expr, P.ArrayLit):
        for item in expr.items:
            _walk_expr(item, calls, names)
    elif isinstance(expr, P.MapLit):
        for k, v in expr.entries:
            _walk_expr(k, calls, names)
            _walk_expr(v, calls, names)
    elif isinstance(expr, P.Throw):
        _walk_expr(expr.value, calls, names)


def _walk_body(stmts: list[P.Stmt], calls: list[P.Call], names: set[str]) -> None:
    """Collect every call and every locally declared name (shadowing guard)."""
    for st in stmts:
        if isinstance(st, P.VarDecl):
            names.add(st.name)
            _walk_expr(st.init, calls, names)
        elif isinstance(st, P.Assign):
            _walk_expr(st.target, calls, names)
            _walk_expr(st.value, calls, names)
        elif isinstance(st, (P.ExprStmt, P.UseStmt)):
            _walk_expr(st.expr, calls, names)
        elif isinstance(st, P.If):
            for cond, body in st.branches:
                _walk_expr(cond, calls, names)
                _walk_body(body, calls, names)
            if st.else_body is not None:
                _walk_body(st.else_body, calls, names)
        elif isinstance(st, P.Case):
            if st.subject is not None:
                _walk_expr(st.subject, calls, names)
            for when in st.whens:
                for cond in when.conditions:
                    _walk_expr(cond, calls, names)
                _walk_body(when.body, calls, names)
            if st.else_body is not None:
                _walk_body(st.else_body, calls, names)
        elif isinstance(st, P.While):
            _walk_expr(st.cond, calls, names)
            _walk_body(st.body, calls, names)
        elif isinstance(st, P.ForEach):
            names.add(st.var)
            _walk_expr(st.source, calls, names)
            _walk_body(st.body, calls, names)
        elif isinstance(st, P.ForTo):
            names.add(st.var)
            _walk_expr(st.start_expr, calls, names)
            _walk_expr(st.to, calls, names)
            if st.step is not None:
                _walk_expr(st.step, calls, names)
            _walk_body(st.body, calls, names)
        elif isinstance(st, P.Try):
            _walk_body(st.body, calls, names)
            for var, _type, body in st.catches:
                if var:
                    names.add(var)
                _walk_body(body, calls, names)
            if st.finally_body is not None:
                _walk_body(st.finally_body, calls, names)
        elif isinstance(st, P.Scope):
            _walk_body(st.body, calls, names)
        elif isinstance(st, P.Return):
            _walk_expr(st.value, calls, names)


@rule("code/call-arity", "code/call-arity.title", "C", severity=Severity.ERROR)
def call_arity(source: SourceFile) -> Iterable[Diagnostic]:
    """A local call must bind to the method's signature."""
    if source.kind != "xbsl":
        return
    module, errors = parse(source)
    if errors:
        return
    # Signatures: module methods by name; static methods of structures and enums by "Тип.Метод".
    sigs: dict[str, Signature] = {}
    dupes: set[str] = set()

    def note(name: str, m: P.Method) -> None:
        if name in sigs:
            dupes.add(name)
        sigs[name] = _signature(m)

    for m in module.members:
        if isinstance(m, P.Method):
            note(m.name, m)
        elif isinstance(m, (P.Structure, P.Enum)):
            subs = m.members if isinstance(m, P.Structure) else m.methods
            for sub in subs:
                if isinstance(sub, P.Method) and sub.is_static:
                    note(f"{m.name}.{sub.name}", sub)
    calls: list[P.Call] = []
    call_scopes: dict[int, dict[str, Signature | None]] = {}
    call_fields: dict[int, set[str]] = {}
    declared: set[str] = set()
    for m in module.members:
        if isinstance(m, P.Method):
            declared.update(p.name for p in m.params)
            for p in m.params:
                _walk_expr(p.default, calls, declared)
            _walk_body(m.body, calls, declared)
        elif isinstance(m, P.ObjectField):
            if m.init is not None:
                _walk_expr(m.init, calls, declared)
        elif isinstance(m, (P.Structure, P.Enum)):
            subs = m.members if isinstance(m, P.Structure) else m.methods
            # Bare calls resolve the owner's own methods before module methods. Keep
            # overloaded methods and callable fields as shadows without a unique signature.
            owner_sigs: dict[str, Signature | None] = {}
            for sub in subs:
                if isinstance(sub, P.Method):
                    owner_sigs[sub.name] = None if sub.name in owner_sigs else _signature(sub)
                elif isinstance(sub, P.ObjectField):
                    owner_sigs[sub.name] = None
            owner_fields = {sub.name for sub in subs if isinstance(sub, P.ObjectField)}
            first_call = len(calls)
            for sub in subs:
                if isinstance(sub, P.Method):
                    declared.update(p.name for p in sub.params)
                    _walk_body(sub.body, calls, declared)
                elif isinstance(sub, P.ObjectField) and sub.init is not None:
                    _walk_expr(sub.init, calls, declared)
            for call in calls[first_call:]:
                call_scopes[call.start] = owner_sigs
                call_fields[call.start] = owner_fields
    if not calls:
        return

    lm = linemap(source)
    for call in calls:
        if isinstance(call.callee, P.Name):
            name = call.callee.name
            if "::" in name or name in declared:
                continue
        elif (
            isinstance(call.callee, P.Member)
            and isinstance(call.callee.obj, P.Name)
            and not call.callee.safe
        ):
            base = call.callee.obj.name
            if base in declared or base in call_fields.get(call.start, set()):
                continue
            name = f"{base}.{call.callee.name}"
        else:
            continue
        owner_sigs = call_scopes.get(call.start, {}) if isinstance(call.callee, P.Name) else {}
        if name in owner_sigs:
            sig = owner_sigs[name]
            generated = False
        else:
            sig = None if name in dupes else sigs.get(name)
            generated = name in _generated_method_names()
        if sig is None:
            continue
        message = _argument_error(
            name, sig, tuple(arg.name for arg in call.args), generated=generated,
        )
        if message is not None:
            line, col = lm.linecol(call.start)
            yield Diagnostic(source.rel, line, col, "code/call-arity", Severity.ERROR, message)



def _cross_mapper(source: SourceFile) -> dict | None:
    """The map phase: this module's signatures plus its candidate cross-module calls.

    Everything local is settled here (argument names, bases shadowed by a declaration
    or by an own member, `::` bases, positions); the reduce only resolves base names
    against the other modules' signatures and the stdlib shadow set.
    """
    if source.kind != "xbsl":
        return None
    stem = source.rel.replace("\\", "/").rsplit("/", 1)[-1].removesuffix(".xbsl")
    module, errors = parse(source)
    if errors:
        # A broken file gives no candidates, but its stem must still poison the name.
        return {"stem": stem if "." not in stem else None, "sigs": None, "calls": []}
    own: set[str] = set()
    calls: list[P.Call] = []
    call_fields: dict[int, set[str]] = {}
    declared: set[str] = set()
    sigs: dict[str, Signature] = {}
    dupes: set[str] = set()
    for m in module.members:
        if isinstance(m, (P.Method, P.Structure, P.Enum, P.ObjectField)):
            own.add(m.name)
        if isinstance(m, P.Method):
            if m.name in sigs:
                dupes.add(m.name)
            sigs[m.name] = _signature(m)
            declared.update(p.name for p in m.params)
            for p in m.params:
                _walk_expr(p.default, calls, declared)
            _walk_body(m.body, calls, declared)
        elif isinstance(m, P.ObjectField):
            if m.init is not None:
                _walk_expr(m.init, calls, declared)
        elif isinstance(m, (P.Structure, P.Enum)):
            subs = m.members if isinstance(m, P.Structure) else m.methods
            owner_fields = {sub.name for sub in subs if isinstance(sub, P.ObjectField)}
            first_call = len(calls)
            for sub in subs:
                if isinstance(sub, P.Method):
                    declared.update(p.name for p in sub.params)
                    _walk_body(sub.body, calls, declared)
                elif isinstance(sub, P.ObjectField) and sub.init is not None:
                    _walk_expr(sub.init, calls, declared)
            for call in calls[first_call:]:
                call_fields[call.start] = owner_fields
    for d in dupes:
        sigs.pop(d, None)
    lm = None
    candidates: list[tuple[str, str, tuple[str | None, ...], int, int]] = []
    for call in calls:
        callee = call.callee
        if not (
            isinstance(callee, P.Member)
            and isinstance(callee.obj, P.Name)
            and not callee.safe
        ):
            continue
        base = callee.obj.name
        # An owner field is a value receiver, not a same-named project module.
        if ("::" in base or base in declared or base in own
                or base in call_fields.get(call.start, set())):
            continue
        if lm is None:
            lm = linemap(source)
        line, col = lm.linecol(call.start)
        candidates.append((base, callee.name, tuple(arg.name for arg in call.args), line, col))
    if "." in stem and not candidates:
        return None  # an object module and friends: not callable by name, nothing to check
    return {"stem": stem if "." not in stem else None, "sigs": sigs, "calls": candidates}


@rule(
    "code/call-arity-cross", "code/call-arity-cross.title", "D",
    scope="project", severity=Severity.ERROR, mapper=_cross_mapper,
)
def call_arity_cross(facts: dict[str, dict]) -> Iterable[Diagnostic]:
    """`Модуль.Метод(...)` must fit the target module's method signature.

    Signatures come from the project's own module files (the file stem is the callable
    name; dotted stems - object modules and other satellites - are not callable by name).
    A finding needs the base name to resolve to exactly one clean project module and the
    method to exist there. Skipped: stdlib name shadows (Пользователи), duplicated module
    or method names, generated singleton overloads, bases shadowed by a local declaration, broken
    files (both as callers and as signature sources).
    """
    try:
        stdlib_names = set(dataset.load_json("stdlib.json").get("names", ()))
    except Exception:  # noqa: BLE001
        return  # without the catalog a project module cannot be told from a stdlib shadow
    # Module name -> method signatures; None marks an unusable name
    # (a parse-broken file or twin modules in different directories).
    module_sigs: dict[str, dict[str, Signature] | None] = {}
    for fact in facts.values():
        stem = fact["stem"]
        if stem is None:
            continue
        if fact["sigs"] is None or stem in module_sigs:
            module_sigs[stem] = None
        else:
            module_sigs[stem] = fact["sigs"]
    if not any(module_sigs.values()):
        return
    for rel, fact in facts.items():
        for base, method, args, line, col in fact["calls"]:
            if base in stdlib_names:
                continue
            target = module_sigs.get(base)
            if not target:
                continue
            sig = target.get(method)
            if sig is None:
                continue  # no such method there - not this rule's business
            name = f"{base}.{method}"
            message = _argument_error(
                name, sig, args, generated=method in _generated_method_names(),
            )
            if message is not None:
                yield Diagnostic(rel, line, col, "code/call-arity-cross", Severity.ERROR, message)
