"""Tier A: structural file checks (no code parsing)."""

from __future__ import annotations

from collections.abc import Iterable
from functools import lru_cache

from xbsl import dataset, i18n
from xbsl.diagnostics import Diagnostic, Severity
from xbsl.engine import SourceFile, rule
from xbsl.rules.semantics import _MEMBER_TYPE_TAILS, _english_tails, _object_members
from xbsl.rules.yaml_schema import _composed, _mapping_nodes

try:
    import yaml

    _HAVE_YAML = True
except ImportError:  # pragma: no cover
    _HAVE_YAML = False

MESSAGES = {
    "structure/xbsl-pair.title": {
        "ru": "Модуль .xbsl без парного .yaml",
        "en": "Module .xbsl without a paired .yaml",
    },
    "structure/xbsl-pair.missing": {
        "ru": "Нет парного описания {name} для модуля.",
        "en": "No paired descriptor {name} for the module.",
    },
    "yaml/duplicate-key.title": {
        "ru": "Ключ задан в узле дважды",
        "en": "A key is set twice in one node",
    },
    "yaml/duplicate-key.repeat": {
        "ru": "Ключ '{name}' уже задан в этом узле (строка {line}) – повтор молча "
              "вытесняет первое значение, а компилятор отклоняет файл при деплое.",
        "en": "The key '{name}' is already set in this node (line {line}) - the repeat "
              "silently overrides the first value, and the compiler rejects the file on "
              "deploy.",
    },
}
i18n.register(MESSAGES)

#: The `<<` key: YAML 1.1 lets one mapping carry several merge keys, each pulling in
#: another mapping, so a repeated `<<` is legal and is not a duplicate.
_MERGE_TAG = "tag:yaml.org,2002:merge"

@lru_cache(maxsize=1)
def _module_suffixes() -> frozenset[str]:
    """Suffixes of a module that extends a type generated by an element of the project.

    An element generates several types, and a module may extend any of them: the docs of every
    kind ("Типы, порождаемые элементом проекта вида ...") name the object module, the record
    module, the record-set module, the record-key module. Such a module is a separate file -
    `Цены.НаборЗаписей.xbsl` - with no yaml of its own: it is described by `Цены.yaml`. The
    names come from the catalog, so a type generated by a kind added later is covered too.

    In BOTH spellings: an English project writes `Prices.RecordSet.xbsl` where a Russian one
    writes `Цены.НаборЗаписей.xbsl`, and either is described by the project's own `.yaml`.
    Only the object module used to be recognised in English, hand-added here as "Object", so
    every other English module of a generated type was read as a module without a descriptor
    and reported - a finding its Russian twin never got. A count of findings could not see it:
    the English tree that was measured happens to carry object modules alone.
    """
    names = set(_MEMBER_TYPE_TAILS)
    for members in _object_members().values():
        names |= set(members)
    return frozenset(names | _english_tails(frozenset(names)))


dataset.register_reset(_module_suffixes.cache_clear)


def _owner_yaml(source: SourceFile):
    """The descriptor file that owns the module: for `Имя.Объект.xbsl` it is `Имя.yaml`."""
    stem = source.path.stem  # 'Заметки.Объект' or 'Заметки'
    base, _, suffix = stem.rpartition(".")
    if base and suffix in _module_suffixes():
        return source.path.with_name(base + ".yaml")
    return source.path.with_suffix(".yaml")


@rule("structure/xbsl-pair", "structure/xbsl-pair.title", "A", severity=Severity.WARNING)
def xbsl_pair(source: SourceFile) -> Iterable[Diagnostic]:
    # A module (.xbsl) is the code of an element described by a paired .yaml – a lone .xbsl is orphaned.
    # This checks files on disk: for in-memory content (lint_source) we do not check the pairing.
    if source.kind != "xbsl" or not source.path.exists():
        return
    yaml_path = _owner_yaml(source)
    if not yaml_path.exists():
        yield Diagnostic(
            source.rel, 1, 1, "structure/xbsl-pair", Severity.WARNING,
            i18n.t("structure/xbsl-pair.missing", name=yaml_path.name),
        )


@rule("yaml/duplicate-key", "yaml/duplicate-key.title", "A", severity=Severity.ERROR)
def yaml_duplicate_key(source: SourceFile) -> Iterable[Diagnostic]:
    """A scalar key repeated within one YAML mapping.

    The second and later occurrences are flagged, at the position of the repeat, naming the
    key and the line where it was first set. YAML syntax allows the repeat, so `yaml/valid`
    is silent, and the loader keeps only the LAST value - by the time any schema rule reads
    the parsed document, the duplicate has already collapsed into one entry, and the whole
    engine judges a file that is not the one on disk. The compiler is the first to object,
    at deploy time: the platform rejects a property given twice, and the half-merged node
    breeds a wave of induced errors after it. The live case (2026-08-28): a recomposition of
    a form tab lost one list-item dash, the properties of the neighbouring page merged into
    a single node, the linter answered clean - and the deploy fell over. A structural check
    on the composed node graph (`yaml_schema._composed`, cached per source - PyYAML's
    composer keeps the duplicates that the loader folds) catches this before any metamodel
    is consulted, which is why the rule needs no Element data and runs in a public clone.

    Narrowings:

    - non-scalar keys are skipped: the platform serializer never writes a complex key, and
      deciding equality of composed subtrees is not what this rule measures;
    - the merge key is skipped by its tag (`_MERGE_TAG`): several `<<` entries in one
      mapping are legal YAML 1.1, each pulling in another mapping;
    - keys compare by (tag, text), the way the loader tells keys apart: a plain `1` and a
      quoted `1` are an int key and a str key - different entries, not a duplicate. Two
      spellings of one boolean (a plain `true` next to `True`) differ in text and are let
      through - a miss on a key no platform file carries, never a false alarm;
    - a mapping reached through an alias is judged once: `_mapping_nodes` deduplicates the
      anchored node itself, so an anchor used twice does not double the findings.
    """
    if not _HAVE_YAML or source.kind != "yaml":
        return
    root = _composed(source)
    if root is None:
        return
    for mapping in _mapping_nodes(root):
        first_lines: dict[tuple[str, str], int] = {}
        for key, _value in mapping.value:
            if not isinstance(key, yaml.ScalarNode) or key.tag == _MERGE_TAG:
                continue
            ident = (key.tag, key.value)
            line = key.start_mark.line + 1
            if ident not in first_lines:
                first_lines[ident] = line
                continue
            yield Diagnostic(
                source.rel, line, key.start_mark.column + 1,
                "yaml/duplicate-key", Severity.ERROR,
                i18n.t("yaml/duplicate-key.repeat", name=key.value, line=first_lines[ident]),
            )
