Ид: ffeacdec-02d6-4f08-bcfa-be89e9a1861a
РежимСовместимости: 9.0
Поставщик: Acme
Имя: Tasks
Версия: 1.0.0
Представление: "Tasks (demo)"
ПредставлениеПоставщика: "Acme"
ЯзыкиЛокализации: [Русский]
ЯзыкПоУмолчанию: Русский
ЯзыкРазработки: Русский
