"""Runtime access to the interface component ui schema (uischema.json).

The schema is generated by tools/extract_uischema.py from the documentation dataset and
lives next to stdlib.json (see xbsl/dataset.py). It feeds the visual designer: the
component palette and the typed properties panel. The response shapes for the LSP
(`xbsl/uiSchema`) and the MCP (`ui_schema`) are built here so the two surfaces stay
identical:

- catalog(): the palette catalog - every component with its package, abstract and
  container flags and doc snippet, WITHOUT the property lists (compact; a component's
  full schema is a separate request);
- component(name): the full record of one component (properties with type unions, enum
  values, event signatures, slot flags) plus "enums" - the value lists of the
  enumerations referenced by the union types of the component's properties (feeds the
  paired Type+Value editor; omitted when there are none); an unknown name yields
  close_matches instead. A name the PALETTE does not carry but a form yaml still writes -
  a command, a command interface fragment, ЭлементСпискаЗначений - is composed from the
  metamodel or the type catalog (see `_outside_component`); such a record says `source`;
- both return {"available": False} when the dataset has no ui schema (e.g. a public
  checkout without generated data) - the docsAvailable degradation pattern.

Optional fields of the schema records (abstract, container, since, doc, nullable, slot,
enum, default, readonly, conflicts) are omitted when false/unknown - consumers treat an
absent key as false/null. Older uischema.json files without the newer fields keep
working: everything added later is optional. See tools/extract_uischema.py for the full
data shape.
"""

from __future__ import annotations

import difflib
import re
from functools import lru_cache

from xbsl import dataset, metamodel, terms

#: Keys of a component record served by the catalog (props stay out - the palette
#: does not need them, and the full record is one more request away).
_CATALOG_KEYS = ("package", "abstract", "container", "since", "doc", "conflicts")

#: A type name inside a union member: the head identifier with optional dotted facets
#: (mirrors the extractor's _TYPE_REF_RE - generic arguments are scanned too).
_TYPE_NAME_RE = re.compile(r"[А-ЯЁA-Z][0-9A-Za-zА-Яа-яЁё_]*(?:\.[0-9A-Za-zА-Яа-яЁё_]+)*")

#: Sections of the term dictionary a name outside the palette can be written in.
_NAME_SECTIONS = ("types", "facets", "enums")
#: The package path of a qualified name: Std::Interface::Commands::UsualCommand.
_QUALIFIER_RE = re.compile(r"\w+::")
#: A Latin identifier, dotted facets included (BinaryObject.Reference) - a term to translate.
_LATIN_NAME_RE = re.compile(r"[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*")
#: A bound value: the metamodel declares `DataBinding<Boolean>` where yaml writes a Булево block.
_BINDING_RE = re.compile(r"^DataBinding<(.+)>$")


def available(version: str | None = None) -> bool:
    """Whether the ui schema has been generated for the data version."""
    return dataset.has_data_file(dataset.UI_SCHEMA_FILE, version)


def catalog(version: str | None = None) -> dict:
    """The palette catalog: components without property lists, or {"available": False}."""
    schema = dataset.load_ui_schema(version)
    if schema is None:
        return {"available": False}
    components = {
        name: {k: rec[k] for k in _CATALOG_KEYS if k in rec}
        for name, rec in (schema.get("components") or {}).items()
    }
    # The palette groups components by package, and the schema names packages in Russian only
    # (it is derived from the Russian documentation). The English spellings come from the
    # distribution, so an English editor can show an English tree.
    packages = {
        russian: english
        for russian in {rec.get("package") for rec in components.values() if rec.get("package")}
        if (english := package_alias(str(russian)))
    }
    return {
        "available": True,
        "version": (schema.get("meta") or {}).get("element_version"),
        "components": components,
        "packages": packages,
    }


def _union_members(expr: str) -> list[str]:
    """Members of a top-level union: `A|B<C|D>` -> ["A", "B<C|D>"] - a nested union stays inside."""
    members, depth, start = [], 0, 0
    for i, ch in enumerate(expr):
        if ch == "<":
            depth += 1
        elif ch == ">":
            depth -= 1
        elif ch == "|" and depth == 0:
            members.append(expr[start:i])
            start = i + 1
    members.append(expr[start:])
    return [m.strip() for m in members if m.strip()]


def _russian(expr: str) -> str:
    """A platform type expression in the short Russian spellings, unknown names kept as they are.

    The metamodel writes types qualified and in English (`Std::ObjectStorage::BinaryObject.Reference`);
    the palette schema and the sources themselves use the Russian short form. Dotted names are looked
    up whole first - the facet dictionary is keyed by `BinaryObject.Reference`, not by its halves.
    """
    def translate(match: re.Match) -> str:
        token = match.group(0)
        for section in _NAME_SECTIONS:
            found = terms.russian(token, section)
            if found:
                return found
        return token

    return _LATIN_NAME_RE.sub(translate, _QUALIFIER_RE.sub("", expr))


def _metamodel_prop(record: dict) -> dict:
    """One metamodel property in the palette's shape: value types, default, since, allowed values."""
    expr = str(record.get("types") or "").strip()
    if not expr:
        expr = str(record.get("type") or "").strip()
        binding = _BINDING_RE.match(expr)
        if binding:
            expr = binding.group(1).strip()
    out: dict = {"types": [_russian(m) for m in _union_members(expr)]} if expr else {}
    for key in ("default", "since"):
        if record.get(key):
            out[key] = record[key]
    if record.get("options"):  # a closed `kind: type` constraint - the values the property accepts
        out["enum"] = record["options"]
    return out


def _english_forms(name: str) -> list[str]:
    """The name itself plus its English spellings - the metamodel and stdlib key by different ones."""
    forms = [name]
    for section in _NAME_SECTIONS:
        english = terms.english(name, section)
        if english and english not in forms:
            forms.append(english)
    return forms


def _stdlib_props(name: str) -> dict | None:
    """Documented properties of a stdlib type, typed from `member_types`, or None."""
    try:
        catalog = dataset.load_json("stdlib.json")
    except dataset.DatasetError:
        return None
    members = (catalog.get("type_members") or {}).get(name) or {}
    props = members.get("properties") or ()
    if not props:
        return None
    member_types = (catalog.get("member_types") or {}).get(name) or {}
    return {p: ({"types": [member_types[p]]} if p in member_types else {}) for p in props}


@lru_cache(maxsize=None)
def _outside_component(name: str) -> dict | None:
    """A record for a name the palette does not carry, or None when nothing describes it.

    Not everything written in a form yaml is a palette component: commands
    (`ОбычнаяКоманда`, `КомандаСПараметром`), command interface fragments and groups,
    `ЭлементСпискаЗначений` - all are hand-written and their property sets are asked for just
    as often. Three sources answer, in this order:

    - an element KIND is described by the class its `vid2class` mapping names - the same set
      `metadata_schema` serves. Resolving such a name through the term dictionary instead would
      quietly hand out a different, smaller set: `ОбычнаяКоманда` is `UsualCommandDescriptor`
      (13 properties, the envelope included), while the type of the same name is `UsualCommand`
      (8). The record says `metadata_kind` so a caller knows which view it holds;
    - a metamodel class named by the term dictionary - authoritative for what yaml accepts;
    - the stdlib type catalog (`stdlib.json`) for what the metamodel has no class of its own for
      (`ЭлементСпискаЗначений`) - documented members instead of yaml keys.

    The record carries `source`, so a caller can tell it from a palette component.
    """
    if name in metamodel.kinds():
        props = {prop: _metamodel_prop(rec) for prop, rec in metamodel.properties(name).items()}
        if props:
            return {"source": "metamodel", "metadata_kind": True, "props": props}
    for form in _english_forms(name):
        if metamodel.has_class(form):
            props = {
                prop: _metamodel_prop(record)
                for prop, record in metamodel.properties_of_class(form).items()
            }
            if props:
                return {"source": "metamodel", "class": form, "props": props}
    for form in _english_forms(name):
        documented = _stdlib_props(form)
        if documented:
            return {"source": "stdlib", "props": documented}
    return None


@lru_cache(maxsize=1)
def _outside_names() -> tuple[str, ...]:
    """Names `_outside_component` can answer for - the close-matches pool of a miss."""
    names = set(metamodel.kinds())
    for cls in metamodel.class_names():
        names.add(terms.russian(cls, "types") or cls)
    try:
        catalog = dataset.load_json("stdlib.json")
    except dataset.DatasetError:
        catalog = {}
    for name, members in (catalog.get("type_members") or {}).items():
        if members.get("properties"):
            names.add(name)
    return tuple(sorted(names))


@lru_cache(maxsize=None)
def _english_components() -> dict[str, str]:
    """{English name of a component: the name the schema uses}, built FORWARD.

    A form may be written in English - the platform reads it either way - and the rules compare
    against the schema's own (Russian) names. Forward, because the dictionaries are many-to-one
    in reverse and would answer with whichever pair came last.
    """
    schema = dataset.load_ui_schema(None) or {}
    out: dict[str, str] = {}
    for name in (schema.get("components") or {}):
        english = terms.english(name, "types") or terms.common_english(name)
        if english:
            out[english] = name
    # The distribution names the components itself (uiterms.json, extracted from the runtime's
    # own descriptions) - it covers what the compiler dictionary does not, and the two agree
    # wherever both answer, so the dictionary keeps precedence and this only fills the gaps.
    for english, russian in (_ui_terms().get("types") or {}).items():
        if isinstance(english, str) and isinstance(russian, str):
            out.setdefault(english, russian)
    return out


@lru_cache(maxsize=None)
def _english_properties() -> dict[str, str]:
    """{English name of a component property: the name the schema uses}, built FORWARD.

    A name whose English spelling is shared by two different properties is dropped: the file
    would be ambiguous, and guessing is worse than leaving the key as written.
    """
    # The full schema, not catalog(): the light one carries no properties at all.
    schema = dataset.load_ui_schema(None) or {}
    pairs: dict[str, set[str]] = {}
    for record in (schema.get("components") or {}).values():
        for name in (record.get("props") or {}):
            english = terms.common_english(name) or terms.english(name, "properties")
            if english:
                pairs.setdefault(english, set()).add(name)
    resolved = {english: names.pop() for english, names in pairs.items() if len(names) == 1}
    # The pairs the distribution states for the properties, events and methods of the components
    # (uiterms.json). The documentation is Russian-only, so for most of them this is the only
    # source there is - `Видимость` (Visible), `SeoОписание` (SeoDescription), `ОсиX` (XAxes).
    for english, russian in (_ui_terms().get("properties") or {}).items():
        if isinstance(english, str) and isinstance(russian, str):
            resolved.setdefault(english, russian)
    # The structural keys of a form node are not component properties, yet a rule reads them off
    # the same mapping: `Тип` tells which component this is, `Имя` names the node.
    for structural in ("Тип", "Имя"):
        english = terms.common_english(structural)
        if english:
            resolved[english] = structural
    return resolved


def english_property(name: str) -> str | None:
    """The English spelling of a component property, or None when the platform names none."""
    return _russian_properties().get(name)


@lru_cache(maxsize=None)
def _russian_properties() -> dict[str, str]:
    """{the schema's name: its English spelling} - the forward view of _english_properties."""
    return {russian: english for english, russian in _english_properties().items()}


@lru_cache(maxsize=1)
def _ui_terms() -> dict:
    """uiterms.json - the English spellings the documentation does not carry.

    Absent on an older data root: every reader degrades to "no pairs", which is exactly the
    behaviour before the extractor existed.
    """
    try:
        return dataset.load_json("uiterms.json") or {}
    except dataset.DatasetError:
        return {}


def enum_value_aliases(enum: str) -> dict[str, str]:
    """{Russian value: its English spelling} of one enumeration, empty when unknown.

    Per enumeration on purpose: globally the same Russian word answers to several English
    ones (`Обычная` is Common, Normal and Usual in different enumerations).
    """
    values = (_ui_terms().get("enum_values") or {}).get(enum)
    return dict(values) if isinstance(values, dict) else {}


def package_alias(package: str) -> str | None:
    """The English spelling of a component package, or None when the data does not name it."""
    value = (_ui_terms().get("packages") or {}).get(package)
    return value if isinstance(value, str) else None


def property_aliases() -> dict[str, str]:
    """{English property name: the name the schema uses} - for surfaces outside python."""
    return dict(_english_properties())


def component_aliases() -> dict[str, str]:
    """{English component name: the name the schema uses} - for surfaces outside python.

    The form designer of the editor parses the yaml itself and compares component types by
    name; without the pairs an English form renders as a tree of unknown nodes.
    """
    return dict(_english_components())


def canonical_component(name: str) -> str:
    """The component type as the schema names it (`Group` -> `Группа`)."""
    if not name or not name.isascii():
        return name
    return _english_components().get(name, name)


def canonical_property(name: str) -> str:
    """A component property as the schema names it (`Layout` -> `Компоновка`)."""
    if not name or not name.isascii():
        return name
    return _english_properties().get(name, name)


def _reset() -> None:
    _ui_terms.cache_clear()
    _outside_component.cache_clear()
    _outside_names.cache_clear()
    _english_components.cache_clear()
    _english_properties.cache_clear()
    _russian_properties.cache_clear()


dataset.register_reset(_reset)


def _lookup(components: dict, name: str) -> dict | None:
    """The palette record for the name, or a record composed outside the palette."""
    return components.get(name) or _outside_component(name)


def _miss(components: dict, name: str) -> dict:
    """The answer for a name nothing describes: close matches over everything that is describable."""
    pool = [*components, *_outside_names()]
    return {
        "available": True,
        "component": None,
        "close_matches": difflib.get_close_matches(name, pool, n=5, cutoff=0.6),
    }


def _component_enums(rec: dict, enums: dict) -> dict:
    """{name: [values]} of the enumerations referenced by the record's property unions.

    Every name mentioned by any member of any "types" union counts (the dataset's
    top-level enums map is the filter); event and slot-only properties carry no unions
    and contribute nothing. Sorted for a deterministic response.
    """
    used: dict[str, list] = {}
    for prop in (rec.get("props") or {}).values():
        for member in prop.get("types") or ():
            for name in _TYPE_NAME_RE.findall(str(member)):
                entry = enums.get(name)
                if entry is not None and name not in used:
                    used[name] = list(entry.get("values") or [])
    return dict(sorted(used.items()))


def component(name: str, version: str | None = None) -> dict:
    """The full schema of one component, or close matches for an unknown name.

    {"available": True, "component": {"name": ..., ...record...}} on a hit, plus
    "enums": {name: [values]} for the enumerations referenced by the union types of the
    component's properties (the key is omitted when there are none);
    {"available": True, "component": None, "close_matches": [...]} on a miss;
    {"available": False} when the dataset has no ui schema.

    A name outside the palette (a command, a fragment, `ЭлементСпискаЗначений`) is answered
    from the metamodel or the type catalog - see `_outside_component`, the record says which.
    """
    schema = dataset.load_ui_schema(version)
    if schema is None:
        return {"available": False}
    components = schema.get("components") or {}
    rec = _lookup(components, name)
    if rec is None:
        return _miss(components, name)
    out = {"available": True, "component": {"name": name, **rec}}
    enums = _component_enums(rec, schema.get("enums") or {})
    if enums:
        out["enums"] = enums
    return out


def _brief_line(prop: dict, enums: dict) -> str:
    """One line for one property: the type union with enum values inline, the
    nullable/slot markers, or the event signature."""
    if "event" in prop:
        return f"событие {prop['event']}"
    parts = []
    for member in prop.get("types") or ():
        text = str(member)
        entry = enums.get(text)
        if entry is not None:
            values = entry.get("values") or prop.get("enum") or []
            if values:
                text += "{" + "|".join(str(v) for v in values) + "}"
        parts.append(text)
    line = " | ".join(parts) if parts else "?"
    if prop.get("nullable"):
        line += "?"
    if prop.get("slot"):
        line += " [slot]"
    return line


def component_brief(name: str, version: str | None = None) -> dict:
    """The compact cut of component(): one line per property instead of the full records.

    The line carries the type union with enum values inline, the nullable/slot markers
    and the event signatures - a fraction of the full schema's size, enough for "does
    the property exist / what values does it take". The full record of one property is
    component_property()'s business.
    """
    schema = dataset.load_ui_schema(version)
    if schema is None:
        return {"available": False}
    components = schema.get("components") or {}
    rec = _lookup(components, name)
    if rec is None:
        return _miss(components, name)
    enums = schema.get("enums") or {}
    head_keys = ("package", "abstract", "container", "doc", "source", "class", "metadata_kind")
    head = {k: rec[k] for k in head_keys if k in rec}
    props = {p: _brief_line(record, enums) for p, record in (rec.get("props") or {}).items()}
    return {"available": True, "component": {"name": name, **head, "props": props}}


def component_property(name: str, prop_name: str, version: str | None = None) -> dict:
    """The full record of ONE property of a component, with the enums its union references.

    {"available": True, "component": name, "property": {"name": ..., ...record...}} on a
    hit (plus "enums" when the union references any); an unknown property answers with
    close matches over the component's property names.
    """
    schema = dataset.load_ui_schema(version)
    if schema is None:
        return {"available": False}
    components = schema.get("components") or {}
    rec = _lookup(components, name)
    if rec is None:
        return _miss(components, name)
    props = rec.get("props") or {}
    prop = props.get(prop_name)
    if prop is None:
        return {
            "available": True,
            "component": name,
            "property": None,
            "close_matches": difflib.get_close_matches(prop_name, props, n=5, cutoff=0.6),
        }
    out = {"available": True, "component": name, "property": {"name": prop_name, **prop}}
    enums = _component_enums({"props": {prop_name: prop}}, schema.get("enums") or {})
    if enums:
        out["enums"] = enums
    return out
